name: Upload
description: Upload a video to YouTube

inputs:
  version:
    description: 'Version of the yutu binary to download'
    required: false
    default: ''
  credential:
    description: 'Base64 encoded credential to authenticate with the YouTube API'
    required: true
  token:
    description: 'Base64 encoded token to authenticate with the YouTube API'
    required: true
  file:
    description: 'Path to the video file to upload'
    required: true
  title:
    description: 'Title of the video, use filename if not provided'
    required: false
    default: ''
  desc:
    description: 'Description of the video'
    required: false
    default: ''
  tags:
    description: 'Comma separated list of tags for the video'
    required: false
    default: ''
  rate:
    description: 'Rating of the video: like, dislike or none'
    required: false
    default: ''
  comment:
    description: 'Comment to post on the video'
    required: false
    default: ''
  output:
    description: 'Output format: json, yaml or silent'
  rest-flags:
    description: 'Flags passed to the command/subcommand'
    required: true

outputs:
  response:
    description: 'Response from the yutu insert command'
    value: ${{ steps.upload.outputs.response }}

runs:
  using: composite
  steps:
    - id: upload
      uses: eat-pray-ai/youtube-action@main
      with:
        version: ${{ inputs.version }}
        credential: ${{ inputs.credential }}
        token: ${{ inputs.token }}
        command: video
        subcommand: insert
        flags: '-f ${{ inputs.file }} -t ${{ inputs.title }} -d "${{ inputs.desc }}" -T ${{ inputs.tags }} -o ${{ inputs.output }} ${{ inputs.rest-flags }}'
    - id: vid
      shell: bash
      continue-on-error: true
      run: |
        video_id=$(echo ${{ steps.upload.outputs.response }} | jq '.id')
        echo "video_id=$video_id" >> $GITHUB_OUTPUT
    - id: rate
      if: ${{ inputs.rate != '' }}
      uses: eat-pray-ai/youtube-action@main
      with:
        credential: ${{ secrets.YOUTUBE_CREDENTIAL }}
        token: ${{ secrets.YOUTUBE_TOKEN }}
        command: video
        subcommand: rate
        flags: '-i ${{ steps.vid.outputs.video_id }} -r like'
    - id: comment
      if: ${{ inputs.comment != '' }}
      uses: eat-pray-ai/youtube-action@main
      with:
        credential: ${{ secrets.YOUTUBE_CREDENTIAL }}
        token: ${{ secrets.YOUTUBE_TOKEN }}
        command: commentThread
        subcommand: insert
        flags: '-a ${{ vars.YOUTUBE_CHANNEL_ID }} -c ${{ vars.YOUTUBE_CHANNEL_ID }} -v ${{ steps.vid.outputs.video_id }} -t "${{ steps.generate.outputs.comment }}"'
